### ISSUE TITLE
Warning about options were not recognized by any processor on `compileTestJava` task

### ISSUE THREAD

**Issue by x80486** [AkaZver/mapstruct-plugin#9]
I have a small project that uses `MapStruct` with `Lombok`. I integrated your plugin (which works like a charm :partying_face:), but I see these warnings popping up all the time:

```shell
[x80486@uplink:~/Workshop/Development/java-flink-sandbox]$ ./gradlew clean check 
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
> Task :clean
> Task :generateEffectiveLombokConfig
> Task :compileJava
> Task :processResources
> Task :classes
> Task :generateTestEffectiveLombokConfig

> Task :compileTestJava
warning: The following options were not recognized by any processor: '[mapstruct.verbose, mapstruct.defaultInjectionStrategy, mapstruct.unmappedTargetPolicy, mapstruct.suppressGeneratorVersionInfoComment, mapstruct.defaultComponentModel, mapstruct.suppressGeneratorTimestamp]'
1 warning

> Task :processTestResources
> Task :testClasses
> Task :test
> Task :check

BUILD SUCCESSFUL in 8s
8 actionable tasks: 8 executed
```

I completely understand it's just a warning, but at the same time I don't know for sure if it's something caused by `MapStruct` itself, or because the plugin is not registering correctly (to name it somehow) those.

I'm just applying the plugin via the `plugins` block without any additional configuration. I'm also using Gradle `7.4` — as you can see in the execution logs.

I do have this task though (not sure if it's overwriting anything):

```groovy
tasks.withType(JavaCompile) {
  final def arguments = ["-parameters"]
  options.compilerArgs.addAll(arguments)
  options.encoding(StandardCharsets.UTF_8 as String)
}
```

**Comment by AkaZver** [comment]
Hello, [x80486](https://github.com/x80486)!

I took a look at your problem and found that part of code in `MapstructPlugin` that works with compiler args added them to all existing tasks of type `JavaCompile` (compileJava, compileTestJava, compileIntegrationTestJava, etc). We need mapstruct only in `annotationProcessor` configuration and not in `testAnnotationProcessor` or `integrationTestAnnotationProcessor` so I decided to focus only on `compileJava` task and problem gone.

I tested fixed version on my work project and log seems fine:
```
> Configure project :
...
> Task :bootBuildInfo
> Task :generateMainEffectiveLombokConfig1
> Task :compileJava
> Task :processResources UP-TO-DATE
> Task :classes
> Task :generateTestEffectiveLombokConfig1
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources UP-TO-DATE
> Task :testClasses UP-TO-DATE
> Task :test
...
> Task :jacocoTestReport
BUILD SUCCESSFUL in 17s
9 actionable tasks: 6 executed, 3 up-to-date
```

Please, take a look at version 1.0.1 and give me a feedback :)

**Comment by x80486** [comment]
Awesome! The warnings are gone!

```shell
[x80486@uplink:~/Workshop/Development/java-flink-sandbox]$ ./gradlew clean check 
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
> Task :clean UP-TO-DATE
> Task :generateEffectiveLombokConfig
> Task :compileJava
> Task :processResources
> Task :classes
> Task :generateTestEffectiveLombokConfig
> Task :compileTestJava
> Task :processTestResources
> Task :testClasses
> Task :test
> Task :check

BUILD SUCCESSFUL in 8s
8 actionable tasks: 7 executed, 1 up-to-date
```

...and everything-`MapStruct` works like before as well. Thanks for fixing it! :tropical_drink:
